### ISSUE TITLE
Appreciation and question

### ISSUE THREAD

**Issue by iomazzoli7** [LotroCompanion/lotro-data#1]
Hi,
I am amazed and I really appreciate your efforts in mantaining this database of all the stuff of LOTRO. Thanks for doing this, really!
I wanted to ask about how u are producing all the datas, if it is not too much to ask: are you taking advantage of the exposed APIs through your own written java, or it is some other way u are extracting all those infos (well, all of the game)? This is so well done, and I'm really curious about if such effort would be within my reach too to do something like this!

**Comment by dmorcellet** [comment]
Hi. Thanks.
This data is automatically generated. AFAIK there is no API to grab this data. This is the result of years of work on understanding the format and contents of the DAT files.
So to the question "is it within my reach": it depends on your overall competence level in RE and programming, and it would require at lot of time. Next question is: why would you do something that's already done? For instance, if we think of doing this for another game then:
1) would probably be easier (lotro data is completely proprietary but inherits from previous/other games like Asheron's Call and Dungeon&Dragon Online
2) other games may have more/less data. Lotro is an old game with "geological" layers of data. Newer game have less history and so more direct design. Lotro has suffered the passing of time and numerous game updates.
3) could be impossible (lotro data is estonishly widely accessible on client side)
Feel free to join the discord, or contact me at lotrocompanion@gmail.com

**Comment by iomazzoli7** [comment]
Thanks for the reply! Your understanding and handling of the .dat files is amazing then.
My skills in programming are not very developed on the java side, so I guess I will stick with reading your wonderful documentation. So, keep up the good work! I joined happily the discord!
